#!/usr/bin/env python3
"""Provider-free contract tests for the paid target probe admission boundary."""
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
import datetime as dt
import gzip
import http.server
import threading


ROOT = Path(__file__).resolve().parents[2]
BENCH = ROOT / "eval" / "bench"
PROBE_PATH = BENCH / "target-contract-probe.py"


def load_probe():
    spec = importlib.util.spec_from_file_location("target_contract_probe", PROBE_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class TargetContractProbeTest(unittest.TestCase):
    def setUp(self):
        self.temp = Path(tempfile.mkdtemp())
        self.probe = load_probe()
        self._probe_run = self.probe.subprocess.run
        self.qwen_stub = self.temp / "qwen-stub"
        self.qwen_stub.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        self.qwen_stub.chmod(0o700)
        self.source = ROOT / "tools" / "tests" / "fixtures" / "target-contract-source"
        self.root = self.temp / "probe"
        self.rate_snapshot = self.temp / "rate.json"
        rate = {"schema": 1, "run_tag": "target-contract-probe",
                "effective_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
                "source": "local-fixture", "prompt_rub_per_token": 0.0, "completion_rub_per_token": 0.0}
        rate["sha256"] = self._sha_bytes(self.probe.canonical(rate))
        self.rate_snapshot.write_text(json.dumps(rate), encoding="utf-8")
        self.args = self.probe.PrepareArgs(
            root=self.root, source_corpus=self.source, provider_base_url="http://127.0.0.1:9",
            route="paid-route", secret_ref="SHERLOCK_API_KEY", requested_model="deepseek-v4-20260901",
            expected_returned_identity="deepseek-v4-20260901",
            identity_mode="provider_pinned_version", qwen_bin=str(self.qwen_stub), arm="target",
            rate_snapshot=self.rate_snapshot,
        )

    def tearDown(self):
        # The real runner seals its trace inputs read-only.  Restore test-temp
        # ownership before unittest removes the isolated fixture tree.
        self.probe.subprocess.run = self._probe_run
        for parent, dirs, files in os.walk(self.temp, topdown=False):
            for name in files:
                os.chmod(Path(parent) / name, 0o600)
            for name in dirs:
                os.chmod(Path(parent) / name, 0o700)
            os.chmod(parent, 0o700)
        shutil.rmtree(self.temp)

    def test_prepare_is_secret_free_and_seals_exact_manifest_assets(self):
        result = self.probe.prepare(self.args, secret_reader=self._tripwire)
        self.assertEqual(self.trips, [])
        manifest = json.loads((self.root / "probe-manifest.json").read_text())
        self.assertEqual(set(manifest), self.probe.PROBE_MANIFEST_KEYS)
        self.assertEqual(manifest["action"], "target_contract_probe")
        for name in ("target-profile.json", "corporate-settings.json", "probe-budget.json", "probe-rate-snapshot.json", "fixture-manifest.json",
                     "input-package.json", "probe-manifest.json"):
            self.assertTrue((self.root / name).is_file(), name)
        self.assertEqual(result["manifest_sha256"], self._sha(self.root / "probe-manifest.json"))
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.prepare(self.args)

    def test_skill_tree_digest_ignores_generated_python_bytecode(self):
        skill = self.temp / "skill"
        tools = skill / "tools"
        tools.mkdir(parents=True)
        source = tools / "check.py"
        source.write_text("VALUE = 1\n", encoding="utf-8")
        expected = self.probe._tree_digest(skill)

        cache = tools / "__pycache__"
        cache.mkdir()
        (cache / "check.cpython-312.pyc").write_bytes(b"generated bytecode")
        (tools / "legacy.pyc").write_bytes(b"generated legacy bytecode")
        (tools / "legacy.pyo").write_bytes(b"generated optimized bytecode")
        self.assertEqual(self.probe._tree_digest(skill), expected)

        source.write_text("VALUE = 2\n", encoding="utf-8")
        self.assertNotEqual(self.probe._tree_digest(skill), expected)

    def test_skill_tree_digest_still_rejects_unsafe_cache_members(self):
        skill = self.temp / "skill"
        cache = skill / "tools" / "__pycache__"
        cache.mkdir(parents=True)
        (skill / "tool.py").write_text("VALUE = 1\n", encoding="utf-8")
        os.symlink(skill / "tool.py", cache / "escaped.pyc")

        with self.assertRaisesRegex(self.probe.ProbeFailure, "unsafe tree member"):
            self.probe._tree_digest(skill)

    def test_rate_snapshot_is_validated_before_root_creation_and_bound_in_manifest(self):
        self.rate_snapshot.write_text('{"schema":1}\n', encoding="utf-8")
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.prepare(self.args)
        self.assertFalse(self.root.exists())
        rate = {"schema": 1, "run_tag": "target-contract-probe",
                "effective_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
                "source": "local-fixture", "prompt_rub_per_token": 0.0, "completion_rub_per_token": 0.0}
        rate["sha256"] = self._sha_bytes(self.probe.canonical(rate))
        self.rate_snapshot.write_text(json.dumps(rate), encoding="utf-8")
        self.probe.prepare(self.args)
        manifest = json.loads((self.root / "probe-manifest.json").read_text())
        self.assertEqual(manifest["rate_snapshot_sha256"], self._sha(self.root / "probe-rate-snapshot.json"))

    def test_authorize_binds_raw_bytes_action_expiry_and_single_use_nonce(self):
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        digest = self._sha(manifest)
        row = self.probe.authorize(manifest, digest, self.root / "nonces")
        self.assertEqual(row["action"], "target_contract_probe")
        with self.assertRaisesRegex(self.probe.ProbeFailure, "APPROVAL_REPLAYED"):
            self.probe.authorize(manifest, digest, self.root / "nonces")

    def test_authorization_binds_canonical_trace_programs_and_exact_nonce_record(self):
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        digest = self._sha(manifest)
        nonce_root = self.root / "nonces"
        self.probe.authorize(manifest, digest, nonce_root)
        auth = json.loads((self.root / "action-authorization.json").read_text())
        self.assertEqual(auth["action_nonce"], json.loads(manifest.read_text())["nonce"])
        self.assertEqual(auth["manifest_raw_sha256"], digest)
        self.assertEqual(auth["probe_root"], str(self.root.resolve()))
        self.assertEqual(auth["trace_path"], str((self.root / "probe-work" / "runs" / "target-contract-probe").resolve()))
        nonce_path = nonce_root / (auth["action_nonce"] + ".json")
        self.assertEqual(auth["nonce_record_path"], str(nonce_path.resolve()))
        self.assertEqual(auth["nonce_record_sha256"], self._sha(nonce_path))
        self.assertEqual(auth["nonce_root"], str(nonce_root.resolve()))
        self.assertEqual(auth["bench_status_sha256"], self._sha(BENCH / "bench-status.py"))
        self.assertEqual(auth["run_verdict_sha256"], self._sha(BENCH / "run-verdict.py"))

    def test_concurrent_authorization_consumes_nonce_exactly_once(self):
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        digest = self._sha(manifest)
        command = [sys.executable, str(PROBE_PATH), "authorize", "--manifest", str(manifest),
                   "--operator-approved-probe", digest, "--nonce-root", str(self.root / "nonces")]
        first = subprocess.Popen(command, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        second = subprocess.Popen(command, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        outcomes = []
        for child in (first, second):
            stdout, stderr = child.communicate(timeout=10)
            outcomes.append("accepted" if child.returncode == 0 else stderr.strip())
        outcomes.sort()
        self.assertEqual(outcomes, ["APPROVAL_REPLAYED", "accepted"])

    def test_refusals_happen_before_secret_proxy_runner_or_network(self):
        for case in ("missing_approval", "wrong_hash", "expired", "wrong_action",
                     "tampered_profile", "tampered_fixture", "used_nonce", "missing_rates"):
            with self.subTest(case=case):
                root = self.temp / case
                args = self.probe.PrepareArgs(**dict(self.args.__dict__, root=root))
                self.probe.prepare(args)
                manifest = root / "probe-manifest.json"
                if case in ("expired", "wrong_action"):
                    row = json.loads(manifest.read_text())
                    row["expires_at" if case == "expired" else "action"] = (
                        "2000-01-01T00:00:00Z" if case == "expired" else "other")
                    manifest.write_bytes(self.probe.canonical(row) + b"\n")
                elif case == "tampered_profile":
                    (root / "target-profile.json").write_text("{}")
                elif case == "tampered_fixture":
                    (root / "fixture-manifest.json").write_text("{}")
                elif case == "missing_rates":
                    (root / "probe-budget.json").write_text("{}")
                digest = self._sha(manifest)
                if case == "missing_approval":
                    digest = ""
                if case == "wrong_hash":
                    digest = "0" * 64
                if case == "used_nonce":
                    self.probe.authorize(manifest, digest, root / "nonces")
                with self.assertRaises(self.probe.ProbeFailure):
                    self.probe.run(manifest, digest, root / "nonces", secret_reader=self._tripwire,
                                   proxy_starter=self._tripwire, runner=self._tripwire)
                self.assertEqual(self.trips, [])

    def test_identity_modes_are_narrow_and_missing_identity_is_terminal(self):
        self.assertEqual(self.probe.audit_identity("provider_pinned_version", "deepseek-v4-20260901",
                                                   ["deepseek-v4-20260901"]),
                         "provider_pinned_version")
        self.assertEqual(self.probe.audit_identity("alias_unresolved", "deepseek-v4-flash",
                                                   ["deepseek-v4-flash"]), "alias_unresolved")
        for returned in ([], [None], ["deepseek-v4-pro"]):
            with self.assertRaisesRegex(self.probe.ProbeFailure, "TARGET_IDENTITY"):
                self.probe.audit_identity("alias_unresolved", "deepseek-v4-flash", returned)

    def test_authorized_run_starts_contact_path_once_with_retries_disabled(self):
        self.probe.prepare(self.args)
        observed = []
        def secret(reference):
            observed.append(("secret", reference))
            return "test-only"
        def proxy(profile, token, budget):
            observed.append(("proxy", profile["requested_model"], token, Path(budget).name))
            return "localhost-only"
        def runner(**kwargs):
            observed.append(("runner", kwargs["retries"], kwargs["proxy"], kwargs["profile_path"].name))
            return {"started": True}
        result = self.probe.run(self.root / "probe-manifest.json",
                                self._sha(self.root / "probe-manifest.json"), self.root / "nonces",
                                secret_reader=secret, proxy_starter=proxy, runner=runner)
        self.assertEqual(result, {"started": True})
        self.assertEqual(observed[-1], ("runner", 0, "localhost-only", "target-profile.json"))

    def test_audit_failure_writes_result_but_never_receipt(self):
        self.probe.prepare(self.args)
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"
        trace.mkdir(parents=True)
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.audit(trace)
        self.assertTrue((trace / "probe-result.json").is_file())
        self.assertFalse((trace / "target-contract-receipt.json").exists())

    def test_receipt_is_atomic_no_replace_when_audit_accepts_all_bound_evidence(self):
        self.probe.prepare(self.args)
        self.probe.authorize(self.root / "probe-manifest.json",
                             self._sha(self.root / "probe-manifest.json"), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"
        self._accepted_trace(trace)
        result = self.probe.audit(trace)
        receipt = trace / "target-contract-receipt.json"
        self.assertTrue(result["accepted"])
        self.assertTrue(receipt.is_file())
        self.assertEqual(self._sha(receipt), (trace / "target-contract-receipt.json.sha256").read_text().strip())
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.audit(trace)

    def test_round5_receipt_binds_raw_authorization_and_complete_terminal_observation(self):
        """Replacing raw authorization bytes or omitting terminal facts is a receipt bug."""
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        self.probe.authorize(manifest, self._sha(manifest), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"
        self._accepted_trace(trace)
        self.probe.audit(trace)
        receipt = json.loads((trace / "target-contract-receipt.json").read_text())
        authorization_raw = (trace / "action-authorization.json").read_bytes()
        self.assertEqual(receipt["action_authorization_sha256"], hashlib.sha256(authorization_raw).hexdigest())
        self.assertEqual(receipt["run_verdict_sha256"], hashlib.sha256((trace / "run-verdict.json").read_bytes()).hexdigest())
        self.assertTrue(receipt["authenticated"])
        self.assertEqual(receipt["authority"], "operator-approved-target-probe")
        self.assertEqual(receipt["status_exit_code"], 0)
        self.assertIn("primary_failure", receipt)
        self.assertIn("terminal_observation", receipt)
        self.assertIn("rate_assurance", receipt)

    def test_commit_marker_is_last_and_binds_exact_receipt_and_checksum_bytes(self):
        """An accepted receipt is inert until its last durable result marker."""
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        self.probe.authorize(manifest, self._sha(manifest), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"
        self._accepted_trace(trace)
        self.assertTrue(self.probe.audit(trace)["accepted"])
        receipt = trace / "target-contract-receipt.json"
        checksum = trace / "target-contract-receipt.json.sha256"
        marker = json.loads((trace / "probe-result.json").read_text())
        self.assertTrue(marker["accepted"])
        self.assertEqual(marker["receipt_sha256"], self._sha(receipt))
        self.assertEqual(marker["receipt_checksum_sha256"], self._sha(checksum))
        self.assertEqual(marker["receipt_checksum"], checksum.read_text().strip())

    def test_receipt_has_complete_raw_evidence_schema(self):
        """Every receipt claim names the raw bytes or observation it binds."""
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        self.probe.authorize(manifest, self._sha(manifest), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"
        self._accepted_trace(trace)
        self.probe.audit(trace)
        receipt = json.loads((trace / "target-contract-receipt.json").read_text())
        required = {"action_authorization_sha256", "probe_manifest_sha256", "run_verdict_sha256",
                    "gate_sha256", "final_report_sha256", "ledger_sha256",
                    "request_body_tree_sha256", "response_body_tree_sha256", "probe_prompt_sha256",
                    "probe_budget_sha256", "probe_rate_snapshot_sha256", "rate_snapshot",
                    "returned_identities", "usage", "cost_inputs", "authenticated", "authority",
                    "status_exit_code", "attempt_exit_code", "driver_exit_code", "gate_exit_codes",
                    "wrapper_exit_code", "primary_failure", "terminal_observation", "rate_assurance",
                    "budget_assurance", "provider_billed_calls", "provider_billed_rub"}
        self.assertTrue(required.issubset(receipt))
        self.assertEqual(receipt["probe_prompt_sha256"], self._sha(trace / "probe" / "prompt.txt"))
        self.assertEqual(receipt["probe_budget_sha256"], self._sha(trace / "probe-budget.json"))
        self.assertEqual(receipt["probe_rate_snapshot_sha256"], self._sha(trace / "probe-rate-snapshot.json"))
        self.assertEqual(receipt["provider_billed_calls"], None)
        self.assertEqual(receipt["provider_billed_rub"], None)

    def test_task3_usage_accepts_ordinary_totals_but_rejects_inconsistent_or_negative_fields(self):
        for index, (extra, accepted) in enumerate((({"total_tokens": 2, "prompt_tokens_details": {"cached_tokens": 0}}, True),
                                                    ({"total_tokens": 3}, False), ({"total_tokens": -1}, False),
                                                    ({"prompt_tokens_details": {"cached_tokens": -1}}, False))):
            with self.subTest(extra=extra):
                root = self.temp / ("usage-" + str(index))
                args = self.probe.PrepareArgs(**dict(self.args.__dict__, root=root))
                self.probe.prepare(args)
                self.probe.authorize(root / "probe-manifest.json", self._sha(root / "probe-manifest.json"), root / "nonces")
                trace = root / "probe-work" / "runs" / "target-contract-probe"; self._accepted_trace(trace, root)
                response = trace / ("0" * 32 + ".a1.res.json.gz")
                payload = {"model": "deepseek-v4-20260901", "usage": {"prompt_tokens": 1, "completion_tokens": 1, **extra}}
                with gzip.open(response, "wb") as handle: handle.write(json.dumps(payload).encode())
                journal = json.loads((trace / "upstream-completed.jsonl").read_text()); journal["usage"] = payload["usage"]
                (trace / "upstream-completed.jsonl").write_text(json.dumps(journal) + "\n")
                body = trace / "response-bodies" / "one.json"
                body_row = json.loads(body.read_text()); body_row["usage"] = payload["usage"]
                body.write_text(json.dumps(body_row))
                if accepted:
                    self.assertTrue(self.probe.audit(trace)["accepted"])
                else:
                    with self.assertRaises(self.probe.ProbeFailure): self.probe.audit(trace)

    def test_hardlinked_receipt_and_accepted_marker_failure_leave_one_rejection(self):
        """Rollback unlinks canonical leaves by held root fd even when linked."""
        self.probe.prepare(self.args)
        self.probe.authorize(self.root / "probe-manifest.json", self._sha(self.root / "probe-manifest.json"), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"
        self._accepted_trace(trace)
        original = self.probe._write_result
        outside = self.temp / "receipt-hardlink.json"
        def fail_accepted(destination, payload, **kwargs):
            if payload.get("accepted"):
                os.link(destination / "target-contract-receipt.json", outside)
                raise OSError("injected accepted marker failure")
            return original(destination, payload, **kwargs)
        self.probe._write_result = fail_accepted
        try:
            with self.assertRaises(self.probe.ProbeFailure):
                self.probe.audit(trace)
        finally:
            self.probe._write_result = original
        self.assertFalse((trace / "target-contract-receipt.json").exists())
        self.assertFalse((trace / "target-contract-receipt.json.sha256").exists())
        self.assertFalse((trace / "receipt-nonces").exists())
        self.assertTrue(outside.exists())
        results = list(trace.glob("probe-result.json"))
        self.assertEqual(len(results), 1)
        self.assertFalse(json.loads(results[0].read_text())["accepted"])

    def test_round5_prepare_seals_exact_prompt_bytes(self):
        self.probe.prepare(self.args)
        manifest = json.loads((self.root / "probe-manifest.json").read_text())
        prompt = self.root / "probe" / "prompt.txt"
        self.assertTrue(prompt.is_file())
        self.assertEqual(manifest["prompt_sha256"], hashlib.sha256(prompt.read_bytes()).hexdigest())

    def test_round5_prepare_never_uses_pathname_staging(self):
        self.assertNotIn("tempfile", self.probe.prepare.__code__.co_names)
        self.probe.prepare(self.args)

    def test_round5_audit_rejects_legacy_ledger_without_task3_journal(self):
        self.probe.prepare(self.args)
        self.probe.authorize(self.root / "probe-manifest.json", self._sha(self.root / "probe-manifest.json"), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"; self._accepted_trace(trace)
        (trace / "upstream-completed.jsonl").unlink()
        self.assertFalse((trace / "upstream-completed.jsonl").exists())
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.audit(trace)

    def test_round5_orphaned_receipt_is_cleaned_without_accepted_commit_marker(self):
        self.probe.prepare(self.args)
        self.probe.authorize(self.root / "probe-manifest.json", self._sha(self.root / "probe-manifest.json"), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"; self._accepted_trace(trace)
        self.probe.audit(trace)
        (trace / "probe-result.json").unlink()
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.audit(trace)
        self.assertFalse((trace / "target-contract-receipt.json").exists())

    def test_round5_missing_secret_does_not_consume_nonce(self):
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        nonce = json.loads(manifest.read_text())["nonce"]
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.run(manifest, self._sha(manifest), self.root / "nonces",
                           secret_reader=lambda _: (_ for _ in ()).throw(RuntimeError("missing test secret")),
                           proxy_starter=self._tripwire, runner=self._tripwire)
        self.assertFalse((self.root / "nonces" / (nonce + ".json")).exists())

    def test_run_uses_only_preconsume_snapshot_after_original_inputs_are_replaced(self):
        """No caller pathname remains authoritative once snapshots are frozen."""
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        observed = {}
        def mutate_then_supply_secret(_):
            (self.root / "target-profile.json").unlink()
            (self.root / "probe" / "prompt.txt").unlink()
            shutil.rmtree(self.root / "fixture")
            (self.root / "probe-rate-snapshot.json").unlink()
            return "local-test-secret"
        def runner(**kwargs):
            observed.update({name: str(value) for name, value in kwargs.items() if name.endswith("path") or name == "fixture"})
            self.assertIn("sealed-input", str(kwargs["profile_path"]))
            self.assertIn("sealed-input", str(kwargs["fixture"]))
            self.assertIn("sealed-input", str(kwargs["rate_snapshot_path"]))
            self.assertEqual(json.loads(kwargs["profile_path"].read_text())["route"], "paid-route")
            self.assertTrue((kwargs["profile_path"].parent / "probe" / "prompt.txt").is_file())
            return {"route": "paid-route"}
        self.assertEqual(self.probe.run(manifest, self._sha(manifest), self.root / "nonces",
                                        secret_reader=mutate_then_supply_secret,
                                        proxy_starter=lambda *_: {"local": True}, runner=runner)["route"], "paid-route")
        self.assertTrue(observed)

    def test_audit_rejects_symlinked_response_tree_and_keeps_receipt_absent(self):
        self.probe.prepare(self.args)
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"
        self._accepted_trace(trace)
        (trace / "response-bodies" / "alias.json").symlink_to(trace / "response-bodies" / "one.json")
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.audit(trace)
        self.assertFalse((trace / "target-contract-receipt.json").exists())

    def test_adversarial_review_regressions_fail_closed_before_or_after_contact(self):
        # These compact cases cover the nine review categories: forged audit,
        # mutable fixture, nonce burn, aliases, strict budget/exits/identity,
        # receipt transaction, and the provider-safe CLI contract.
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        digest = self._sha(manifest)
        (self.root / "fixture" / "Security.jsonl").write_text("attacker\n")
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.run(manifest, digest, self.root / "nonces", secret_reader=self._tripwire,
                           proxy_starter=self._tripwire, runner=self._tripwire)
        self.assertEqual(self.trips, [])
        # Dependency rejection must not consume approval.
        (self.root / "fixture" / "Security.jsonl").write_bytes(
            (self.source / "Security.jsonl").read_bytes())
        self.probe.authorize(manifest, digest, self.root / "nonces")

        root = self.temp / "forged"
        args = self.probe.PrepareArgs(**dict(self.args.__dict__, root=root))
        self.probe.prepare(args)
        trace = root / "probe-work"; self._accepted_trace(trace)
        (trace / "work" / "report.md").write_text("ok\n")
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.audit(trace)
        self.assertFalse((trace / "target-contract-receipt.json").exists())

    def test_cli_prepare_json_and_run_refusal_never_contact(self):
        root = self.temp / "cli"
        command = [sys.executable, str(PROBE_PATH), "prepare", "--root", str(root),
                   "--source-corpus", str(self.source), "--provider-base-url", "http://127.0.0.1:9",
                   "--route", "paid-route", "--secret-ref", "SHERLOCK_API_KEY",
                   "--requested-model", "deepseek-v4-20260901", "--expected-returned-identity",
                   "deepseek-v4-20260901", "--identity-mode", "provider_pinned_version",
                   "--qwen-bin", str(self.qwen_stub), "--arm", "target", "--rate-snapshot", str(self.rate_snapshot), "--json"]
        done = subprocess.run(command, text=True, capture_output=True)
        self.assertEqual(done.returncode, 0, done.stderr)
        self.assertEqual(json.loads(done.stdout)["root"], str(root))

    def test_cli_run_rejects_runner_substitution_even_for_local_stub(self):
        self.probe.prepare(self.args)
        marker = self.temp / "runner-marker.json"
        stub = self.temp / "runner.py"
        stub.write_text("#!/usr/bin/env python3\nimport json,os\nopen(os.environ['MARKER'],'w').write(json.dumps({k:os.environ[k] for k in ('SHERLOCK_TARGET_PROFILE','SHERLOCK_PROBE_FIXTURE','SHERLOCK_PROBE_BUDGET','SHERLOCK_PROBE_WORK','SHERLOCK_MAX_RETRIES')}))\n")
        stub.chmod(0o700)
        env = dict(os.environ, SHERLOCK_API_KEY="test-only", MARKER=str(marker))
        done = subprocess.run([sys.executable, str(PROBE_PATH), "run", "--manifest", str(self.root / "probe-manifest.json"),
                               "--operator-approved-probe", self._sha(self.root / "probe-manifest.json"),
                               "--nonce-root", str(self.root / "nonces"), "--runner-command", str(stub)],
                              text=True, capture_output=True, env=env)
        self.assertNotEqual(done.returncode, 0)
        self.assertFalse(marker.exists())

    def test_cli_local_transport_uses_the_real_runner_and_never_fabricates_a_report(self):
        """A provider-free refusal proves the production runner branch is selected."""
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        done = subprocess.run([sys.executable, str(PROBE_PATH), "run", "--manifest", str(manifest),
                               "--operator-approved-probe", self._sha(manifest), "--nonce-root", str(self.root / "nonces"),
                               "--transport-base-url", "http://127.0.0.1:9/v1", "--json"],
                              text=True, capture_output=True,
                              env=dict(os.environ, SHERLOCK_API_KEY="test-only"), timeout=30)
        self.assertNotEqual(done.returncode, 0)
        self.assertNotIn("TARGET_PROBE_TEST_MODE_REQUIRED", done.stderr)
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"
        self.assertFalse((trace / "run-manifest.json").exists())
        self.assertFalse((trace / "work" / "report.md").exists())

    def test_provider_free_e2e_uses_real_runner_lane_proxy_and_task7(self):
        """One local call crosses the same sealed path as a paid target probe."""
        canonical_report = (ROOT / "tools" / "tests" / "fixtures" /
                            "target-contract-reports" / "canonical.md").read_text(encoding="utf-8")
        qwen = self.temp / "sealed-local-qwen.py"
        tools = ROOT / "skills" / "v44" / "tools"
        qwen.write_text("""#!/usr/bin/env python3
import json, os, subprocess, sys, urllib.request
from pathlib import Path
if '--sherlock-flag-probe-sentinel' in sys.argv:
    raise SystemExit(0)
try:
    prompt = sys.argv[sys.argv.index('-p') + 1]
except (ValueError, IndexError):
    raise SystemExit('Qwen did not receive a raw prompt')
request = urllib.request.Request(os.environ['OPENAI_BASE_URL'].rstrip('/') + '/chat/completions',
    data=json.dumps({'model': os.environ.get('SHERLOCK_QWEN_MODEL', 'deepseek-v4-20260901'),
                     'messages': [{'role': 'user', 'content': prompt}], 'max_tokens': 7}).encode(),
    headers={'Authorization': 'Bearer fixture-token', 'Content-Type': 'application/json'})
with urllib.request.urlopen(request, timeout=10) as response:
    observed = json.loads(response.read().decode())
assert observed['model'] == 'deepseek-v4-20260901', observed
work, corpus = Path('work'), Path('corpus')
work.mkdir(exist_ok=True)
subprocess.run(['python3', %r, str(corpus), '--out', str(work), '--worklist-cap', '10', '--rate-cap', '0', '--jobs', '1'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
(work / 'rules.tsv').write_text('', encoding='utf-8')
# The two-line contract corpus has no statistically rare mapper candidate.  A
# Qwen run nevertheless has to leave a normal, inspectable ledger: seed one
# finding from the sealed source, then use the real cursor for its only write.
# This is fixture output, not runner-provided evidence or a canonical report
# copy; the row's address and quote are verified by the real generic gates.
if not [line for line in (work / 'worklist.tsv').read_text(encoding='utf-8').splitlines()
        if line and not line.startswith('#')]:
    security = (corpus / 'Security.jsonl').read_text(encoding='utf-8').splitlines()[2]
    system = (corpus / 'System.jsonl').read_text(encoding='utf-8').splitlines()[0]
    (work / 'worklist.tsv').write_text(
        '# id\\tвердикт\\tось\\tссылка\\tчастота\\tзапись\\n'
        'g1\\t?\\trare\\tSecurity.jsonl:3\\tn=1\\t' + security + '\\n'
        'g2\\t?\\trare\\tSystem.jsonl:1\\tn=1\\t' + system + '\\n', encoding='utf-8')
for source in (work / 'worklist.tsv').read_text(encoding='utf-8').splitlines():
    if not source or source.startswith('#'):
        continue
    row = source.split('\\t')
    path, line = row[3].rsplit(':', 1)
    quote = (corpus / path).read_text(encoding='utf-8').splitlines()[int(line) - 1]
    subprocess.run(['python3', %r, 'next', '--work', str(work)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
    subprocess.run(['python3', %r, 'verdict', '--work', str(work), '--id', row[0],
                    '--cell', 'N n=1 %%s «%%s»' %% (row[3], quote)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
# A blank work tree gets its report only from the local model response.  The
# fixture never copies a canonical report into the runner work directory.
if (work / 'report.md').exists():
    raise SystemExit('report was not blank before model output')
(work / 'report.md').write_text(observed['choices'][0]['message']['content'], encoding='utf-8')
print(json.dumps([{'type':'result','result':'ok','is_error':False,'session_id':'1234567890abcdef',
                   'num_turns':1,'usage':{'input_tokens':3,'output_tokens':2}}]))
""" % (str(tools / "logmap.py"), str(tools / "worklist.py"), str(tools / "worklist.py")), encoding="utf-8")
        qwen.chmod(0o700)

        seen = []
        class Upstream(http.server.BaseHTTPRequestHandler):
            def do_POST(inner):
                length = int(inner.headers["Content-Length"])
                payload = json.loads(inner.rfile.read(length))
                prompt_raw = payload['messages'][0]['content'].encode('utf-8')
                seen.append({'payload': payload, 'prompt_sha256': hashlib.sha256(prompt_raw).hexdigest()})
                response = json.dumps({"id": "fixture-response", "object": "chat.completion",
                    "model": "deepseek-v4-20260901", "choices": [{"index": 0, "message": {"role": "assistant", "content": canonical_report}, "finish_reason": "stop"}],
                    "usage": {"prompt_tokens": 3, "completion_tokens": 2}}).encode()
                inner.send_response(200); inner.send_header("Content-Type", "application/json")
                inner.send_header("Content-Length", str(len(response))); inner.end_headers()
                inner.wfile.write(response)
            def log_message(inner, *_args):
                pass
        server = http.server.ThreadingHTTPServer(("127.0.0.1", 0), Upstream)
        thread = threading.Thread(target=server.serve_forever, daemon=True); thread.start()
        try:
            root = (self.temp / "e2e").resolve()
            args = self.probe.PrepareArgs(**dict(self.args.__dict__, root=root, qwen_bin=str(qwen), arm="v44",
                provider_base_url="http://127.0.0.1:%d/v1" % server.server_port))
            self.probe.prepare(args)
            manifest = root / "probe-manifest.json"
            done = subprocess.run([sys.executable, str(PROBE_PATH), "run", "--manifest", str(manifest),
                "--operator-approved-probe", self._sha(manifest), "--nonce-root", str(root / "nonces"),
                "--transport-base-url", "http://127.0.0.1:%d/v1" % server.server_port, "--json"],
                text=True, capture_output=True, timeout=120, env=dict(os.environ, SHERLOCK_API_KEY="fixture-token"))
        finally:
            server.shutdown(); thread.join(timeout=5); server.server_close()
        trace_hint = root / "probe-work" / "runs" / "target-contract-probe"
        diagnostic = {}
        gates_path = trace_hint / "gates.json"
        upstream_path = trace_hint.parent / "target-contract-probe.upstream.jsonl"
        if upstream_path.is_file():
            diagnostic["target-contract-probe.upstream.jsonl"] = upstream_path.read_text(encoding="utf-8", errors="replace")
        result_path = trace_hint / "probe-result.json"
        if result_path.is_file():
            diagnostic["target-contract-probe/probe-result.json"] = result_path.read_text(encoding="utf-8", errors="replace")
        outer_result = root / "probe-work" / "probe-result.json"
        if outer_result.is_file():
            diagnostic["probe-work/probe-result.json"] = outer_result.read_text(encoding="utf-8", errors="replace")
        budget_path = trace_hint / "upstream-budget-state.json"
        if budget_path.is_file():
            diagnostic["target-contract-probe/upstream-budget-state.json"] = budget_path.read_text(encoding="utf-8", errors="replace")
        for name, path in (("status.json", trace_hint / "status.json"),
                           ("upstream.proxy.err", trace_hint.parent / "target-contract-probe.upstream.proxy.err")):
            if path.is_file():
                diagnostic["target-contract-probe/" + name] = path.read_text(encoding="utf-8", errors="replace")
        diagnostic["upstream-requests-seen"] = repr(len(seen))
        projection = subprocess.run([sys.executable, str(ROOT / "eval" / "bench" / "run-verdict.py"),
                                     str(trace_hint), "--target-probe", "--json"], text=True, capture_output=True)
        diagnostic["fresh-task7"] = repr((projection.returncode, projection.stdout, projection.stderr))
        if gates_path.is_file():
            gates = json.loads(gates_path.read_text())
            cite = gates.get("gates", {}).get("citecheck", {}).get("json", {})
            diagnostic["target-contract-probe/citecheck-summary.json"] = json.dumps({
                key: cite.get(key) for key in ("blocking", "defects", "ledger", "summary", "outcomes", "report_evidence")}, ensure_ascii=False)
            diagnostic["target-contract-probe/gates-summary.json"] = json.dumps({
                "verdict": gates.get("verdict"),
                **{name: {"exit_code": row.get("exit_code"), "blocking": row.get("blocking")}
                for name, row in gates.get("gates", {}).items()}}, ensure_ascii=False)
        self.assertEqual(done.returncode, 0, (done.stdout, done.stderr, diagnostic))
        result = json.loads(done.stdout); trace = Path(result["trace"])
        self.assertTrue(result["audit"]["accepted"])
        sealed_prompt = trace / "probe" / "prompt.txt"
        self.assertEqual(len(seen), 1); self.assertEqual(seen[0]["payload"]["model"], "deepseek-v4-20260901")
        self.assertEqual(seen[0]["prompt_sha256"], hashlib.sha256(sealed_prompt.read_bytes()).hexdigest())
        self.assertEqual(seen[0]["payload"]["messages"][0]["content"], sealed_prompt.read_text(encoding="utf-8"))
        rows = [json.loads(line) for line in (trace / "upstream-completed.jsonl").read_text().splitlines()]
        self.assertEqual(len(rows), 1); row = rows[0]
        self.assertEqual(row["requested_model"], row["sent_model"])
        self.assertEqual(row["sent_model"], row["returned_model"])
        self.assertRegex(row["action_attempt_id"], row["request_id"] + r"\.a1")
        self.assertTrue((trace / "upstream-bodies" / row["body_request_file"]).is_file())
        self.assertTrue((trace / "upstream-bodies" / row["body_response_file"]).is_file())
        with gzip.open(trace / "upstream-bodies" / row["body_request_file"], "rt") as handle:
            self.assertEqual(json.load(handle)["model"], "deepseek-v4-20260901")
        with gzip.open(trace / "upstream-bodies" / row["body_response_file"], "rt") as handle:
            response = json.load(handle)
        self.assertEqual(response["model"], row["returned_model"])
        self.assertEqual(response["usage"], {"prompt_tokens": 3, "completion_tokens": 2})
        budget = json.loads((trace / "upstream-budget-state.json").read_text())
        self.assertEqual(budget["schema"], 2)
        self.assertEqual(budget["limits"], {key: self.probe.DEFAULT_BUDGET[key] for key in (
            "max_provider_calls", "max_prompt_tokens", "max_completion_tokens", "max_wall_time_s", "max_estimated_cost_rub")})
        profile = json.loads((trace / "target-profile.json").read_text())
        self.assertEqual(profile["limits"]["requests"],
                         budget["limits"]["max_provider_calls"])
        self.assertGreaterEqual(budget["limits"]["max_prompt_tokens"],
                                profile["limits"]["requests"] * profile["session_token_limit"])
        self.assertGreaterEqual(budget["limits"]["max_completion_tokens"],
                                profile["limits"]["requests"] * profile["max_output_tokens"])
        self.assertLessEqual(profile["limits"]["requests"] * budget["projected"]["wall_time_s"],
                             budget["limits"]["max_wall_time_s"])
        self.assertEqual(budget["rate_snapshot"], json.loads((trace / "probe-rate-snapshot.json").read_text()))
        # The legacy failure cap protects the lane's retry loop; it is not a
        # paid-envelope limit and so must not appear in schema-2's five limits.
        self.assertEqual(budget["limits"].get("max_consecutive_provider_failures"), None)
        gate_outputs = json.loads((trace / "gates.json").read_text())
        self.assertEqual(set(gate_outputs["gates"]), set(self.probe.GATES))
        self.assertEqual(set(json.loads((trace / "probe-gates.json").read_text())), set(self.probe.GATES))
        self.assertTrue(json.loads((trace / "probe-oracle.json").read_text())["accepted"])
        verdict = json.loads((trace / "run-verdict.json").read_text())
        self.assertEqual(set(verdict), {"schema", "run_tag", "state", "phase", "finished", "successful",
                         "report_correct", "report_correctness_scope", "authenticated", "authority", "failures",
                         "metrics", "improvements", "attempt_exit_code", "driver_exit_code", "wrapper_exit_code",
                         "gate_exit_codes", "primary_failure", "terminal_observation"})
        self.assertTrue(verdict["successful"]); self.assertEqual(verdict["authority"], "operator-approved-target-probe")
        self.assertEqual({name: verdict["gate_exit_codes"][name] for name in self.probe.GATES},
                         {name: 0 for name in self.probe.GATES})
        self.assertTrue((trace / "work" / "report.md").is_file())
        report = (trace / "work" / "report.md").read_text(encoding="utf-8")
        self.assertEqual(re.findall(r"^## (F-(?:AUTH-EXTERNAL|INVENTORY-SERVICE|REPORTED-CONTEXT|TIMELINE-LINK))$", report, re.M),
                         ["F-AUTH-EXTERNAL", "F-INVENTORY-SERVICE", "F-REPORTED-CONTEXT", "F-TIMELINE-LINK"])

    def test_manifest_created_at_must_be_aware_and_bound_before_contact(self):
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        row = json.loads(manifest.read_text())
        row["created_at"] = "2000-01-01T00:00:00"
        row["expires_at"] = "2099-01-01T00:00:00Z"
        manifest.write_bytes(self.probe.canonical(row) + b"\n")
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.run(manifest, self._sha(manifest), self.root / "nonces",
                           secret_reader=self._tripwire, proxy_starter=self._tripwire, runner=self._tripwire)
        self.assertEqual(self.trips, [])

    def test_run_rejects_undeclared_fixture_member_before_secret(self):
        """A sealed fixture is a closed tree, not merely declared leaf hashes."""
        self.probe.prepare(self.args)
        (self.root / "fixture" / "undeclared.jsonl").write_text("attacker\n")
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.run(self.root / "probe-manifest.json", self._sha(self.root / "probe-manifest.json"),
                           self.root / "nonces", secret_reader=self._tripwire,
                           proxy_starter=self._tripwire, runner=self._tripwire)
        self.assertEqual(self.trips, [])

    def test_safe_read_rejects_a_parent_symlink(self):
        """A no-follow leaf check is insufficient when an ancestor aliases it."""
        source = self.temp / "source"; source.mkdir()
        (source / "asset.json").write_text("{}\n")
        alias = self.temp / "alias"
        alias.symlink_to(source, target_is_directory=True)
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.safe_read_regular(alias / "asset.json")

    def test_nonce_and_publication_reject_parent_symlinks(self):
        """A parent alias cannot redirect single-use or receipt publication."""
        self.probe.prepare(self.args)
        outside = self.temp / "outside"; outside.mkdir()
        nonce_alias = self.temp / "nonce-alias"; nonce_alias.symlink_to(outside, target_is_directory=True)
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.authorize(self.root / "probe-manifest.json", self._sha(self.root / "probe-manifest.json"), nonce_alias)
        self.assertEqual(list(outside.iterdir()), [])
        receipt_alias = self.temp / "receipt-alias"; receipt_alias.symlink_to(outside, target_is_directory=True)
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe._atomic_no_replace(receipt_alias / "receipt.json", b"{}\n")
        self.assertEqual(list(outside.iterdir()), [])

    def test_receipt_checksum_interruption_rolls_back_receipt_and_seals_rejection(self):
        """An interrupted accepted publication leaves one rejected terminal result."""
        self.probe.prepare(self.args)
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"; self._accepted_trace(trace)
        original = self.probe._atomic_no_replace
        def interrupt(path, data):
            if str(path).endswith("target-contract-receipt.json.sha256"):
                raise self.probe.ProbeFailure("TARGET_CONTRACT_FAILED", "injected checksum interruption")
            return original(path, data)
        self.probe._atomic_no_replace = interrupt
        try:
            with self.assertRaises(self.probe.ProbeFailure):
                self.probe.audit(trace)
        finally:
            self.probe._atomic_no_replace = original
        self.assertFalse((trace / "target-contract-receipt.json").exists())
        self.assertFalse((trace / "target-contract-receipt.json.sha256").exists())
        self.assertFalse(json.loads((trace / "probe-result.json").read_text())["accepted"])

    def test_precontact_run_refusal_writes_one_terminal_result(self):
        """Even a malformed manifest leaves an auditable terminal outcome."""
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"
        manifest.write_text("{}\n")
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.run(manifest, self._sha(manifest), self.root / "nonces",
                           secret_reader=self._tripwire, proxy_starter=self._tripwire, runner=self._tripwire)
        result = self.root / "probe-result.json"
        self.assertTrue(result.is_file())
        self.assertFalse(json.loads(result.read_text())["accepted"])

    def test_audit_rejects_forged_budget_identity_and_body_aliases(self):
        """One trace call has one bounded sent/returned identity and owned bodies."""
        for mutation in ("budget", "identity", "body-alias"):
            with self.subTest(mutation=mutation):
                root = self.temp / ("audit-" + mutation)
                args = self.probe.PrepareArgs(**dict(self.args.__dict__, root=root))
                self.probe.prepare(args)
                trace = root / "probe-work"; self._accepted_trace(trace, root)
                if mutation == "budget":
                    budget = json.loads((trace / "upstream-budget-state.json").read_text())
                    budget["limits"]["max_provider_calls"] = 999
                    (trace / "upstream-budget-state.json").write_bytes(self.probe.canonical(budget))
                elif mutation == "identity":
                    ledger = json.loads((trace / "ledger.json").read_text())
                    ledger["sent_models"] = ["other-model"]
                    (trace / "ledger.json").write_bytes(self.probe.canonical(ledger))
                else:
                    first = trace / "request-bodies" / "one.json"
                    os.link(first, trace / "response-bodies" / "alias.json")
                with self.assertRaises(self.probe.ProbeFailure):
                    self.probe.audit(trace)
                self.assertFalse((trace / "target-contract-receipt.json").exists())

    def test_run_revalidates_snapshot_after_secret_callback(self):
        """A callback cannot substitute bytes after the final pre-contact check."""
        self.probe.prepare(self.args)
        observed = []
        def secret(_reference):
            sealed = self.root / "probe-work" / "sealed-input" / "target-profile.json"
            profile = json.loads(sealed.read_text())
            profile["route"] = "substituted-route"
            sealed.write_bytes(self.probe.canonical(profile) + b"\n")
            return "test-only"
        def proxy(profile, _token, _budget):
            observed.append(profile["route"])
            return "localhost-only"
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.run(self.root / "probe-manifest.json", self._sha(self.root / "probe-manifest.json"),
                           self.root / "nonces", secret_reader=secret, proxy_starter=proxy,
                           runner=self._tripwire)
        self.assertEqual(observed, [])

    def test_run_revalidates_snapshot_after_proxy_callback(self):
        """The proxy callback is not allowed to substitute last-use input bytes."""
        self.probe.prepare(self.args)
        observed = []
        def proxy(_profile, _token, _budget):
            sealed = self.root / "probe-work" / "sealed-input" / "target-profile.json"
            row = json.loads(sealed.read_text())
            row["route"] = "after-final-check"
            sealed.write_bytes(self.probe.canonical(row) + b"\n")
            return {"route": "localhost-only"}
        def runner(**kwargs):
            observed.append(json.loads(kwargs["profile_path"].read_text())["route"])
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.run(self.root / "probe-manifest.json", self._sha(self.root / "probe-manifest.json"),
                           self.root / "nonces", secret_reader=lambda _: "test-only",
                           proxy_starter=proxy, runner=runner)
        self.assertEqual(observed, [])

    def test_local_transport_parser_rejects_prefix_and_nonloopback(self):
        """Local integration override is an exact parsed loopback URL."""
        for value in ("http://127.0.0.1.evil.invalid:9/v1", "https://not-local.invalid/v1",
                      "http://user@127.0.0.1:9/v1", "ftp://127.0.0.1:9"):
            with self.subTest(value=value):
                with self.assertRaises(self.probe.ProbeFailure):
                    self.probe.validate_test_transport(value)
        self.assertEqual(self.probe.validate_test_transport("http://127.0.0.1:9/v1"), "http://127.0.0.1:9/v1")

    def test_alias_authorization_is_thirty_minutes_not_twenty_four_hours(self):
        args = self.probe.PrepareArgs(**dict(self.args.__dict__, root=self.temp / "alias",
            identity_mode="alias_unresolved", expected_returned_identity="deepseek-v4"))
        self.probe.prepare(args)
        manifest = args.root / "probe-manifest.json"
        row = json.loads(manifest.read_text())
        created = self.probe._iso(row["created_at"])
        self.assertLessEqual(self.probe._iso(row["expires_at"]) - created, __import__("datetime").timedelta(minutes=30))

    def test_timeout_writes_one_terminal_result(self):
        self.probe.prepare(self.args)
        def timeout(**_kwargs):
            raise subprocess.TimeoutExpired(["local-stub"], 1)
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.run(self.root / "probe-manifest.json", self._sha(self.root / "probe-manifest.json"),
                           self.root / "nonces", secret_reader=lambda _: "test-only",
                           proxy_starter=lambda *_: {}, runner=timeout)
        row = json.loads((self.root / "probe-work" / "probe-result.json").read_text())
        self.assertFalse(row["accepted"])
        self.assertEqual(row["failure"], "TARGET_CONTRACT_FAILED")

    def test_audit_correlates_actual_body_rows_and_task7_verdict(self):
        """Ledger summaries cannot replace the raw request/response evidence."""
        self.probe.prepare(self.args)
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"; self._accepted_trace(trace)
        (trace / "run-verdict.json").write_text(json.dumps({"schema": 1, "run_tag": trace.name,
            "state": "succeeded", "finished": True, "successful": True,
            "report_correct": True, "failures": [], "metrics": {}}))
        (trace / "response-bodies" / "one.json").write_text(json.dumps({"call_id": "other",
            "returned_identity": "other", "usage": {"prompt_tokens": 1, "completion_tokens": 1}}))
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.audit(trace)

    def test_cli_refuses_arbitrary_runner_command(self):
        """The paid CLI may select only its sealed controller/runner path."""
        self.probe.prepare(self.args)
        done = subprocess.run([sys.executable, str(PROBE_PATH), "run", "--manifest",
                               str(self.root / "probe-manifest.json"), "--operator-approved-probe",
                               self._sha(self.root / "probe-manifest.json"), "--nonce-root",
                               str(self.root / "nonces"), "--runner-command", "/usr/bin/true", "--json"],
                              text=True, capture_output=True,
                              env=dict(os.environ, SHERLOCK_API_KEY="test-only"))
        self.assertNotEqual(done.returncode, 0)

    # Round 4 regressions.  These deliberately describe the real state-machine
    # contract, rather than accepting the old test-only runner fixture.
    def test_audit_requires_a_durable_consumed_action_nonce_and_uses_a_new_receipt_nonce(self):
        self.probe.prepare(self.args)
        trace = self.root / "probe-work"
        self._accepted_trace(trace)
        with self.assertRaisesRegex(self.probe.ProbeFailure, "TARGET_CONTRACT_FAILED"):
            self.probe.audit(trace)
        self.probe.authorize(self.root / "probe-manifest.json",
                             self._sha(self.root / "probe-manifest.json"), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"
        self._accepted_trace(trace)
        result = self.probe.audit(trace)
        receipt = json.loads((trace / "target-contract-receipt.json").read_text())
        self.assertTrue(result["accepted"])
        self.assertNotEqual(receipt["nonce"], json.loads((self.root / "probe-manifest.json").read_text())["nonce"])

    def test_audit_accepts_the_actual_task7_finished_exit_schema(self):
        self.probe.prepare(self.args)
        self.probe.authorize(self.root / "probe-manifest.json",
                             self._sha(self.root / "probe-manifest.json"), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"
        self._accepted_trace(trace)
        (trace / "run-verdict.json").write_text(json.dumps({
            "schema": 1, "run_tag": trace.name, "state": "finished", "phase": "FINISHED",
            "finished": True, "successful": True, "report_correct": True,
            "report_correctness_scope": "sealed-contract-gates", "authenticated": True, "authority": "operator-approved-target-probe",
            "failures": [], "metrics": {}, "improvements": [],
            "attempt_exit_code": 0, "driver_exit_code": 0,
            "gate_exit_codes": {name: 0 for name in self.probe.GATES},
            "wrapper_exit_code": 0, "primary_failure": None,
            "terminal_observation": "representative target probe completed",
        }))
        self.assertTrue(self.probe.audit(trace)["accepted"])

    def test_audit_sums_each_gzip_proxy_response_and_correlates_calls_and_cost(self):
        self.probe.prepare(self.args)
        self.probe.authorize(self.root / "probe-manifest.json",
                             self._sha(self.root / "probe-manifest.json"), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"; self._accepted_trace(trace)
        # A forged aggregate is never a substitute for the per-call capture.
        body = json.loads((trace / "response-bodies" / "one.json").read_text())
        body["call_id"] = "f" * 32 + ".a1"
        body["usage"] = {"prompt_tokens": 2, "completion_tokens": 2}
        (trace / "response-bodies" / "one.json").write_text(json.dumps(body))
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.audit(trace)

    def test_prepare_rejects_symlink_parent_before_creating_any_entry(self):
        outside = self.temp / "outside"; outside.mkdir()
        parent = self.temp / "aliased-parent"; parent.symlink_to(outside, target_is_directory=True)
        args = self.probe.PrepareArgs(**dict(self.args.__dict__, root=parent / "probe"))
        with self.assertRaises(self.probe.ProbeFailure):
            self.probe.prepare(args)
        self.assertFalse((outside / "probe").exists())

    def test_audit_timeout_still_emits_exactly_one_terminal_result(self):
        self.probe.prepare(self.args)
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"; self._accepted_trace(trace)
        original = self.probe.subprocess.run
        self.probe.subprocess.run = lambda *a, **kw: (_ for _ in ()).throw(subprocess.TimeoutExpired(a[0], 1))
        try:
            with self.assertRaises(self.probe.ProbeFailure):
                self.probe.audit(trace)
        finally:
            self.probe.subprocess.run = original
        self.assertTrue((trace / "probe-result.json").is_file())
        self.assertFalse((self.root / "nonces").exists())

    # Round 5: actual producer schemas and one-way state-machine boundaries.
    def test_round5_audit_consumes_task3_jsonl_gzip_and_actual_task7_projection(self):
        self.probe.prepare(self.args)
        self.probe.authorize(self.root / "probe-manifest.json", self._sha(self.root / "probe-manifest.json"), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"; self._accepted_trace(trace)
        (trace / "ledger.json").unlink()
        request_id = "0" * 32
        request, response = trace / (request_id + ".req.json.gz"), trace / (request_id + ".a1.res.json.gz")
        with gzip.open(request, "wb") as handle:
            handle.write(json.dumps({"model": "deepseek-v4-20260901"}).encode())
        with gzip.open(response, "wb") as handle:
            handle.write(json.dumps({"model": "deepseek-v4-20260901", "usage": {"prompt_tokens": 1, "completion_tokens": 1}}).encode())
        (trace / "upstream-completed.jsonl").write_text(json.dumps({
            "request_id": request_id, "action_attempt_id": request_id + ".a1",
            "body_request_file": request.name, "body_response_file": response.name,
            "action_contact_completed": True,
            "requested_model": "deepseek-v4-20260901", "sent_model": "deepseek-v4-20260901",
            "returned_model": "deepseek-v4-20260901", "usage": {"prompt_tokens": 1, "completion_tokens": 1},
        }) + "\n")
        actual = {"schema": 1, "run_tag": trace.name, "state": "finished", "phase": "FINISHED",
                  "finished": True, "successful": True, "report_correct": True,
                  "report_correctness_scope": "sealed-contract-gates", "authenticated": True,
                  "authority": "operator-approved-target-probe", "failures": [], "metrics": {}, "improvements": [],
                  "attempt_exit_code": 0, "driver_exit_code": 0,
                  "gate_exit_codes": {name: 0 for name in self.probe.GATES}, "wrapper_exit_code": 0,
                  "primary_failure": None, "terminal_observation": "FINISHED"}
        (trace / "run-verdict.json").write_text(json.dumps(actual))
        self.assertTrue(self.probe.audit(trace)["accepted"])

    def test_round5_ambient_conflict_is_refused_before_nonce_consumption(self):
        self.probe.prepare(self.args)
        manifest = self.root / "probe-manifest.json"; old = os.environ.get("SHERLOCK_FORBIDDEN")
        os.environ["SHERLOCK_FORBIDDEN"] = "1"
        try:
            with self.assertRaises(self.probe.ProbeFailure):
                self.probe.run(manifest, self._sha(manifest), self.root / "nonces",
                               secret_reader=self._tripwire, proxy_starter=self._tripwire, runner=self._tripwire)
        finally:
            if old is None: os.environ.pop("SHERLOCK_FORBIDDEN", None)
            else: os.environ["SHERLOCK_FORBIDDEN"] = old
        self.assertFalse((self.root / "nonces").exists())

    def test_round5_failed_publication_has_only_rejected_result_and_no_receipt_nonce(self):
        self.probe.prepare(self.args)
        self.probe.authorize(self.root / "probe-manifest.json", self._sha(self.root / "probe-manifest.json"), self.root / "nonces")
        trace = self.root / "probe-work" / "runs" / "target-contract-probe"; self._accepted_trace(trace)
        original = self.probe._write_result
        self.probe._write_result = lambda *_, **__: (_ for _ in ()).throw(OSError("injected"))
        try:
            with self.assertRaises(self.probe.ProbeFailure): self.probe.audit(trace)
        finally:
            self.probe._write_result = original
        self.assertFalse((trace / "target-contract-receipt.json").exists())
        self.assertFalse((trace / "receipt-nonces").exists())

    def _accepted_trace(self, trace, source_root=None):
        trace.mkdir(parents=True)
        source_root = self.root if source_root is None else source_root
        for name in ("target-profile.json", "corporate-settings.json", "probe-budget.json", "probe-rate-snapshot.json", "fixture-manifest.json",
                     "input-package.json", "probe-manifest.json"):
            shutil.copy2(source_root / name, trace / name)
        if (source_root / "action-authorization.json").is_file():
            shutil.copy2(source_root / "action-authorization.json", trace / "action-authorization.json")
        (trace / "probe").mkdir()
        shutil.copy2(source_root / "probe" / "prompt.txt", trace / "probe" / "prompt.txt")
        shutil.copytree(source_root / "fixture", trace / "fixture")
        (trace / "work").mkdir()
        shutil.copy2(ROOT / "tools" / "tests" / "fixtures" / "target-contract-reports" / "canonical.md",
                     trace / "work" / "report.md")
        fixture_test = ROOT / "tools" / "tests" / "test_target_contract_fixture.py"
        spec = importlib.util.spec_from_file_location("fixture_test_helpers", fixture_test)
        helpers = importlib.util.module_from_spec(spec); spec.loader.exec_module(helpers)
        # The canonical fixture is sealed; generate the v44 worklist from an
        # isolated gate corpus rather than adding a post-seal fixture leaf.
        gate_corpus = trace.parent / ("gate-corpus-" + trace.name)
        shutil.copytree(trace / "fixture", gate_corpus)
        helpers.minimum_ledger(trace / "work", gate_corpus)
        call_id = "0" * 32 + ".a1"
        (trace / "ledger.json").write_text(json.dumps({"provider_calls_observed": 1,
            "usage": {"prompt_tokens": 1, "completion_tokens": 1},
            "returned_identities": ["deepseek-v4-20260901"],
            "sent_models": ["deepseek-v4-20260901"], "call_ids": [call_id]}))
        (trace / "request-bodies").mkdir(); (trace / "response-bodies").mkdir()
        (trace / "request-bodies" / "one.json").write_text(json.dumps({"call_id": call_id,
            "model": "deepseek-v4-20260901"}))
        (trace / "response-bodies" / "one.json").write_text(json.dumps({"call_id": call_id,
            "returned_identity": "deepseek-v4-20260901",
            "usage": {"prompt_tokens": 1, "completion_tokens": 1}}))
        request = trace / (call_id[:32] + ".req.json.gz")
        response = trace / (call_id[:32] + ".a1.res.json.gz")
        with gzip.open(request, "wb") as handle:
            handle.write(json.dumps({"model": "deepseek-v4-20260901"}).encode())
        with gzip.open(response, "wb") as handle:
            handle.write(json.dumps({"model": "deepseek-v4-20260901", "usage": {
                "prompt_tokens": 1, "completion_tokens": 1}}).encode())
        (trace / "upstream-completed.jsonl").write_text(json.dumps({
            "request_id": call_id[:32], "action_attempt_id": call_id,
            "body_request_file": request.name, "body_response_file": response.name,
            "action_contact_completed": True, "requested_model": "deepseek-v4-20260901",
            "sent_model": "deepseek-v4-20260901", "returned_model": "deepseek-v4-20260901",
            "usage": {"prompt_tokens": 1, "completion_tokens": 1}}) + "\n")
        (trace / "run-verdict.json").write_text(json.dumps({"schema": 1, "run_tag": trace.name,
            "state": "finished", "phase": "FINISHED", "finished": True, "successful": True,
            "report_correct": True, "report_correctness_scope": "sealed-contract-gates",
            "authenticated": True, "authority": "operator-approved-target-probe", "failures": [], "metrics": {}, "improvements": [],
            "attempt_exit_code": 0, "driver_exit_code": 0, "wrapper_exit_code": 0,
            "gate_exit_codes": {name: 0 for name in self.probe.GATES}, "primary_failure": None,
            "terminal_observation": "RUN_SUCCEEDED"}))
        # Unit fixtures cannot run the whole controller lifecycle.  Audit still
        # must launch its bound Task7 command; return only this fixture's raw
        # Task7 stdout when that exact command is launched and delegate gates.
        original = self._probe_run
        def fresh_task7(command, *args, **kwargs):
            if (isinstance(command, list) and len(command) >= 2 and
                    Path(command[1]).name == "run-verdict.py"):
                return subprocess.CompletedProcess(command, 0, (trace / "run-verdict.json").read_text(), "")
            return original(command, *args, **kwargs)
        self.probe.subprocess.run = fresh_task7
        effective = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")
        rate = {"schema": 1, "run_tag": trace.name, "effective_at": effective, "source": "local-test",
                "prompt_rub_per_token": 0.0, "completion_rub_per_token": 0.0}
        rate["sha256"] = self._sha_bytes(self.probe.canonical(rate))
        (trace / "upstream-budget-state.json").write_text(json.dumps({"schema": 2,
            "run_tag": trace.name, "updated_at": effective,
            "limits": {key: self.probe.DEFAULT_BUDGET[key] for key in (
                "max_provider_calls", "max_prompt_tokens", "max_completion_tokens",
                "max_wall_time_s", "max_estimated_cost_rub")},
            "budget_assurance": "client_pre_dispatch", "projected": {"provider_calls": 1,
            "prompt_tokens": 1, "completion_tokens": 1, "wall_time_s": 1.0, "estimated_cost_rub": 0.1},
            "observed": {"provider_calls": 1, "prompt_tokens": 1, "completion_tokens": 1},
            "completed_overshoot": {"provider_calls": 0, "prompt_tokens": 0, "completion_tokens": 0},
            "observed_usage_unknown": 0, "completed_attempt_ids": [call_id],
            "verdict": "WITHIN", "reason": None,
            "rate_snapshot": rate}))

    @property
    def trips(self):
        return getattr(self, "_trips", [])

    def _tripwire(self, *args, **kwargs):
        self._trips = self.trips + [args]
        raise AssertionError("contact tripwire invoked")

    @staticmethod
    def _sha(path):
        return hashlib.sha256(Path(path).read_bytes()).hexdigest()

    @staticmethod
    def _sha_bytes(value):
        return hashlib.sha256(value).hexdigest()


if __name__ == "__main__":
    unittest.main()
