#!/usr/bin/env bash
# Re-validate this run with NO reconstruction and no access to the
# original corpus. Generated by run-bench.sh at run-20260906T195846Z-5a428e4e295c.
# arm=v50 dataset=harness-qualification
set -u
HERE="$(cd "$(dirname "$0")" && pwd -P)"
C="$HERE/staged-corpus"   # the tree the model was scored against
T="$HERE/gate-tools"      # the exact grader this run used
R="$HERE/reference"       # the grader DATA it read at grade time
# REFUSE, NEVER FALL BACK. A replay that quietly resolves tools through
# the live checkout re-validates today code, not this run - which is the
# one thing this script exists to prevent. SHERLOCK_GATE_TOOLS may only
# name this trace own grader.
if [ -n "${SHERLOCK_GATE_TOOLS:-}" ]; then
  if [ "$(cd "$SHERLOCK_GATE_TOOLS" 2>/dev/null && pwd -P)" != "$T" ]; then
    echo "refusing: SHERLOCK_GATE_TOOLS points outside this trace" >&2; exit 2
  fi
fi
[ -d "$C" ] || { echo "refusing: no staged-corpus in this trace" >&2; exit 2; }
[ -d "$T" ] || { echo "refusing: no gate-tools in this trace" >&2; exit 2; }
[ -d "$R" ] || { echo "refusing: no reference/ in this trace" >&2; exit 2; }
cd "$HERE" || exit 2
python3 "$T/citecheck.py" work/report.md --corpus "$C" --require-quote --ledger work/worklist.tsv; CITE=$?; echo "citecheck rc=$CITE"
python3 "$T/triagecheck.py" --worklist work/worklist.tsv --rules work/rules.tsv --corpus "$C"; TRIAGE=$?; echo "triagecheck rc=$TRIAGE"
python3 "$T/statecheck.py" --corpus "$C" --report work/report.md; STATE=$?; echo "statecheck rc=$STATE"
# reportcheck reads only the report and its own sealed contract under $R.
python3 "$T/reportcheck.py" work/report.md; REPORTC=$?; echo "reportcheck rc=$REPORTC"
# THE POINT OF A REPLAY: does it reproduce the recorded verdict? Nothing
# used to check, so a divergence looked exactly like a successful replay.
REPLAYED_CITECHECK=$CITE REPLAYED_TRIAGECHECK=$TRIAGE REPLAYED_STATECHECK=$STATE \
  REPLAYED_REPORTCHECK=$REPORTC \
  python3 -c 'import json, os, sys
try:
    recorded = json.load(open("gates.json"))
except Exception as error:
    print("no recorded verdict to compare against: %r" % (error,)); sys.exit(2)
rows = recorded.get("gates") or {}
bad = []
for name in ("citecheck", "triagecheck", "statecheck", "reportcheck"):
    was = rows.get(name, {}).get("exit_code")
    now = os.environ.get("REPLAYED_" + name.upper())
    now = int(now) if now not in (None, "") else None
    if was != now:
        bad.append("%s recorded=%r replayed=%r" % (name, was, now))
print("recorded verdict: %s %s" % (recorded.get("verdict"),
      {k: v.get("exit_code") for k, v in rows.items()}))
if bad:
    print("REPLAY DIVERGED: " + "; ".join(bad)); sys.exit(3)
print("replay reproduced the recorded gate exits")'
